# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python foo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # The name of this job
  validation:

    runs-on: ubuntu-latest

    steps:
    # git checkout into the branch submitted and pull requested.
    - uses: actions/checkout@v2
    # set up the python for running this build job
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
         python-version: 3.7
    # The main part of this workflow
    - name: Run foo.py
      run: |
        python foo.py

